package generator

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// simpleProxyTemplate 简单代理模板（不启用 AOP 时使用）
const simpleProxyTemplate = `// Code generated by goaop. DO NOT EDIT.
package {{.Package}}

import (
	{{- range .Imports}}
	"{{.}}"
	{{- end}}
)

type {{.ProxyName}} struct {
	target *{{.TargetName}}
}

func New{{.ProxyName}}(target *{{.TargetName}}) *{{.ProxyName}} {
	return &{{.ProxyName}}{target: target}
}

{{- range .Methods}}
func (p *{{$.ProxyName}}) {{.Name}}({{.ParamsStr}}) {{.ResultsStr}} {
	return p.target.{{.Name}}({{.ArgsList}})
}
{{- end}}

func init() {
	globalContainer.Register("{{.BeanID}}", core.Factory(func(c core.Container) (any, error) {
		target := &{{.TargetName}}{}
		{{- range .Dependencies}}
		if dep, err := c.Get("{{.}}"); err == nil {
			target.{{.}} = dep.(*{{.}})
		}
		{{- end}}
		return New{{.ProxyName}}(target), nil
	}, reflect.TypeOf(&{{.TargetName}}{})), core.Singleton())
}
`

// aopProxyTemplate AOP 增强代理模板（启用 AOP 时使用）
const aopProxyTemplate = `// Code generated by goaop. DO NOT EDIT.
package {{.Package}}

import (
	{{- range .Imports}}
	"{{.}}"
	{{- end}}
)

type {{.ProxyName}} struct {
	target  *{{.TargetName}}
	aspects []*aop.AspectMeta
}

func New{{.ProxyName}}(target *{{.TargetName}}) *{{.ProxyName}} {
	return &{{.ProxyName}}{
		target:  target,
		aspects: []*aop.AspectMeta{
			{{- range .Aspects}}
			&{
				PointCut: aop.MatchByName("{{.MethodName}}"),
				Advice:   aop.{{.AdviceType}}({{.AdviceFunc}}),
				Order:    {{.Order}},
			},
			{{- end}}
		},
	}
}

{{- range .Aspects}}
func {{.AdviceFunc}}(jp aop.JoinPoint{{if eq .AdviceType "Around"}}, proceed aop.ProceedFunc{{end}}) {{if eq .AdviceType "Around"}}any{{end}} {
	aspect := &{{.AspectName}}{}
	{{- if eq .AdviceType "Before"}}
	aspect.{{.AspectMethodName}}(jp)
	{{- else if eq .AdviceType "After"}}
	aspect.{{.AspectMethodName}}(jp)
	{{- else if eq .AdviceType "Around"}}
	return aspect.{{.AspectMethodName}}(jp, proceed)
	{{- end}}
}
{{- end}}

{{- range .Methods}}
func (p *{{$.ProxyName}}) {{.Name}}({{.ParamsStr}}) {{.ResultsStr}} {
	jp := &aop.MethodInvocation{
		MethodName: "{{.Name}}",
		Func:       p.target.{{.Name}},
		Params:     []any{ {{.ArgsList}} },
		Object:     p.target,
	}
	result := aop.ExecuteChainWithPtrs(jp, p.aspects)
	{{- if .NoReturn}}
	return
	{{- else if .HasMultipleReturns}}
	if tuple, ok := result.([]any); ok {
		{{- if .HasError}}
		if len(tuple) > 0 {
			if err, ok := tuple[len(tuple)-1].(error); ok && err != nil {
				return {{.ReturnValuesWithError}}
			}
		}
		{{- end}}
		return {{.ReturnValuesFromTuple}}
	}
	return {{.ReturnValuesFallback}}
	{{- else if .HasSingleErrorReturn}}
	if err, ok := result.(error); ok {
		return err
	}
	return nil
	{{- else if .HasSingleReturn}}
	if typed, ok := result.({{.SingleReturnType}}); ok {
		return typed
	}
	return nil
	{{- end}}
}
{{- end}}

func init() {
	globalContainer.Register("{{.BeanID}}", core.Factory(func(c core.Container) (any, error) {
		target := &{{.TargetName}}{}
		{{- range .Dependencies}}
		if dep, err := c.Get("{{.}}"); err == nil {
			target.{{.}} = dep.(*{{.}})
		}
		{{- end}}
		return New{{.ProxyName}}(target), nil
	}, reflect.TypeOf(&{{.TargetName}}{})), core.Singleton())
}
`

// adviceAdapterTemplate 通知适配器模板
const adviceAdapterTemplate = `// Code generated by goaop. DO NOT EDIT.
//go:build goaop
// +build goaop

package {{.Package}}

import (
	"github.com/xudefa/go-boot/aop"
)

{{- range .Adapters}}
func {{.FuncName}}(jp aop.JoinPoint{{if .IsAround}}, proceed aop.ProceedFunc{{end}}) {{if .HasReturn}}any{{end}} {
	aspect := &{{.AspectType}}{}
	{{- if .IsAround}}
	return aspect.{{.MethodName}}(jp, proceed)
	{{- else}}
	aspect.{{.MethodName}}(jp)
	{{- end}}
}
{{- end}}
`

// ProxyTemplateData 代理模板数据
type ProxyTemplateData struct {
	Package      string               // 包名
	ProxyName    string               // 代理类名
	TargetName   string               // 目标结构体名
	BeanID       string               // Bean 标识
	Imports      []string             // 导入列表
	Aspects      []AspectTemplateData // 切面数据列表
	Methods      []MethodTemplateData // 方法数据列表
	Dependencies []string             // 依赖列表
}

// AspectTemplateData 切面模板数据
type AspectTemplateData struct {
	MethodName       string // 目标方法名
	AdviceType       string // 通知类型（Before/After/Around 等）
	AdviceFunc       string // 通知函数名
	Order            int    // 切面优先级
	AspectName       string // 切面名称
	AspectMethodName string // 切面方法名
}

// MethodTemplateData 方法模板数据
type MethodTemplateData struct {
	Name                  string // 方法名
	ParamsStr             string // 参数列表字符串
	ResultsStr            string // 返回值列表字符串
	ArgsList              string // 参数名列表字符串
	HasError              bool   // 是否包含 error 返回值
	HasMultipleReturns    bool   // 是否有多个返回值
	HasSingleReturn       bool   // 是否仅有单个非 error 返回值
	HasSingleErrorReturn  bool   // 是否仅有单个 error 返回值
	NoReturn              bool   // 是否无返回值
	SingleReturnType      string // 单返回值类型
	ReturnValues          string // 返回值表达式
	ReturnValuesWithError string // 含 error 的返回值表达式
	ReturnValuesFromTuple string // 从元组解析的返回值表达式
	ReturnValuesFallback  string // 返回值回退表达式
}

// AdviceAdapterTemplateData 通知适配器模板数据
type AdviceAdapterTemplateData struct {
	Package  string              // 包名
	Adapters []AdviceAdapterData // 适配器列表
}

// AdviceAdapterData 通知适配器数据
type AdviceAdapterData struct {
	FuncName   string // 适配器函数名
	AspectType string // 切面类型名
	MethodName string // 切面方法名
	IsAround   bool   // 是否为环绕通知
	HasReturn  bool   // 是否有返回值
}

// TemplateEngine 代码模板引擎
//
// 管理代理代码生成的 Go 模板，支持简单代理和 AOP 增强代理两种模式。
type TemplateEngine struct {
	simpleProxyTemplate *template.Template // 简单代理模板
	aopProxyTemplate    *template.Template // AOP 增强代理模板
	adapterTemplate     *template.Template // 通知适配器模板
}

// NewTemplateEngine 创建代码模板引擎
func NewTemplateEngine() (*TemplateEngine, error) {
	simpleTmpl, err := template.New("simpleProxy").Parse(simpleProxyTemplate)
	if err != nil {
		return nil, fmt.Errorf("failed to parse simple proxy template: %w", err)
	}

	aopTmpl, err := template.New("aopProxy").Parse(aopProxyTemplate)
	if err != nil {
		return nil, fmt.Errorf("failed to parse AOP proxy template: %w", err)
	}

	adapterTmpl, err := template.New("adapter").Parse(adviceAdapterTemplate)
	if err != nil {
		return nil, fmt.Errorf("failed to parse adapter template: %w", err)
	}

	return &TemplateEngine{
		simpleProxyTemplate: simpleTmpl,
		aopProxyTemplate:    aopTmpl,
		adapterTemplate:     adapterTmpl,
	}, nil
}

// GenerateProxy 根据模板数据生成代理代码
//
// enableAOP 为 true 时使用 AOP 增强模板，否则使用简单代理模板。
func (e *TemplateEngine) GenerateProxy(data ProxyTemplateData, enableAOP bool) (string, error) {
	var buf bytes.Buffer
	var tmpl *template.Template

	if enableAOP {
		tmpl = e.aopProxyTemplate
	} else {
		tmpl = e.simpleProxyTemplate
	}

	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute proxy template: %w", err)
	}
	return buf.String(), nil
}

// GenerateAdviceAdapter 生成通知适配器代码
func (e *TemplateEngine) GenerateAdviceAdapter(data AdviceAdapterTemplateData) (string, error) {
	var buf bytes.Buffer
	if err := e.adapterTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute adapter template: %w", err)
	}
	return buf.String(), nil
}

// buildMethodTemplateData 从方法信息构建方法模板数据
func buildMethodTemplateData(method MethodInfo) MethodTemplateData {
	var params []string
	for _, param := range method.Params {
		if param.Name != "" {
			params = append(params, fmt.Sprintf("%s %s", param.Name, param.Type))
		} else {
			params = append(params, param.Type)
		}
	}

	var results []string
	for _, result := range method.Results {
		if result.Name != "" {
			results = append(results, fmt.Sprintf("%s %s", result.Name, result.Type))
		} else {
			results = append(results, result.Type)
		}
	}

	var resultsStr string
	if len(results) > 1 {
		resultsStr = fmt.Sprintf("(%s)", strings.Join(results, ", "))
	} else if len(results) == 1 {
		resultsStr = results[0]
	}

	var argsList []string
	for _, param := range method.Params {
		argsList = append(argsList, param.Name)
	}

	hasError := false
	for _, result := range method.Results {
		if result.Type == "error" {
			hasError = true
			break
		}
	}

	var returnValues []string
	var returnValuesWithError []string
	var returnValuesFromTuple []string
	var returnValuesFallback []string
	for i, result := range method.Results {
		if result.Type == "error" {
			returnValuesWithError = append(returnValuesWithError, "err")
			returnValuesFallback = append(returnValuesFallback, "nil")
		} else {
			if hasError {
				returnValuesWithError = append(returnValuesWithError, fmt.Sprintf("tuple[%d].(%s)", i, result.Type))
			} else {
				returnValues = append(returnValues, fmt.Sprintf("tuple[%d].(%s)", i, result.Type))
			}
			returnValuesFromTuple = append(returnValuesFromTuple, fmt.Sprintf("tuple[%d].(%s)", i, result.Type))
			returnValuesFallback = append(returnValuesFallback, "nil")
		}
	}

	if len(returnValues) == 0 {
		returnValues = append(returnValues, "result")
	}

	if len(returnValuesFallback) == 0 {
		for range method.Results {
			returnValuesFallback = append(returnValuesFallback, "nil")
		}
	}

	if len(returnValuesFromTuple) == 0 {
		returnValuesFromTuple = returnValuesFallback
	}

	if hasError {
		returnValuesFromTuple = append(returnValuesFromTuple, "nil")
	}

	hasMultipleReturns := len(method.Results) > 1
	hasSingleReturn := len(method.Results) == 1 && !hasError
	hasSingleErrorReturn := len(method.Results) == 1 && hasError
	noReturn := len(method.Results) == 0
	singleReturnType := ""
	if hasSingleReturn {
		singleReturnType = method.Results[0].Type
	}

	return MethodTemplateData{
		Name:                  method.Name,
		ParamsStr:             strings.Join(params, ", "),
		ResultsStr:            resultsStr,
		ArgsList:              strings.Join(argsList, ", "),
		HasError:              hasError,
		HasMultipleReturns:    hasMultipleReturns,
		HasSingleReturn:       hasSingleReturn,
		HasSingleErrorReturn:  hasSingleErrorReturn,
		NoReturn:              noReturn,
		SingleReturnType:      singleReturnType,
		ReturnValues:          strings.Join(returnValues, ", "),
		ReturnValuesWithError: strings.Join(returnValuesWithError, ", "),
		ReturnValuesFromTuple: strings.Join(returnValuesFromTuple, ", "),
		ReturnValuesFallback:  strings.Join(returnValuesFallback, ", "),
	}
}
